# Generated by Django 2.1.1 on 2019-03-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='gameId',
            field=models.IntegerField(default=18),
        ),
    ]
