# Generated by Django 2.1.1 on 2019-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190310_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='revealed',
            field=models.CharField(default='nnnnnnnnnn', max_length=400),
        ),
    ]
