# Generated by Django 2.1.1 on 2019-03-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_map_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
