# Generated by Django 2.1.1 on 2019-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_map_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='flag',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100),
        ),
    ]
