# Generated by Django 2.1.1 on 2019-03-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_map_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='flag',
        ),
    ]
